/**
 * Phase-F review round 3 pins for the repl tool's structured-output cap
 * and its truncation-reference store:
 *
 * - the `wait` result variant ACCEPTS `referenced` (round 3: the wait
 *   handler attaches it when refs are requested, but the output
 *   validator's wait branch forbade the field — the produced shape was
 *   rejected with "output does not match a repl result variant"),
 * - refs are WORKSPACE-NAMESPACED (`<project-key>:t<seq>`): a ref from
 *   one project resolves only in its own workspace's store (round 3:
 *   every workspace issued bare `t1`/`t2` ids and the projectless
 *   status search returned the first matching ref across contexts — a
 *   ref from one project could silently return another project's data),
 * - the store NEVER EVICTS an advertised ref (round 3: the old 16-ref
 *   ring dropped still-advertised refs, and the ephemeral
 *   completion/output tails cannot be regenerated by re-reading current
 *   state),
 * - `reset` clears the store (round 3: reset dropped the VM and the
 *   disk store but never cleared `truncationRefs` — old workspace
 *   metadata stayed retrievable after the tool reported the workspace
 *   state was dropped).
 */

import assert from "node:assert/strict";
import { test } from "node:test";

import { capStructuredResult, replToolOutputShape } from "../src/index.js";
import { TruncationRefStore } from "../src/repl-project.js";

test("cumulative continuation refs preserve the ORIGINAL VERBATIM order across repeated halvings (round 4: the chunks used to chain in reverse)", () => {
  const store = new TruncationRefStore("proj-e-555555555555");
  // A pending list big enough to trip the aggregate 10 KB cap across
  // several halving passes (only `pending` is elidable here — the
  // other arrays are empty, so the elision record is deterministic).
  const pending = Array.from(
    { length: 2000 },
    (_, i) => `call-${String(i).padStart(4, "0")}-${'x'.repeat(40)}`,
  );
  const result = capStructuredResult(
    {
      action: "eval",
      projectDir: "/tmp/w",
      output: [],
      outputTruncated: false,
      pending,
      checkpoints: [],
      completed: [],
    },
    store,
  );
  const truncated = (result as { truncated?: Record<string, { elided: number; ref?: string }> }).truncated;
  assert.ok(truncated?.pending?.ref, "the elision advertises a continuation ref");
  const dropped = store.get(truncated!.pending!.ref!)!;
  assert.equal(dropped.length, truncated!.pending!.elided, "the ref holds every elided entry");
  // THE ORDER: the dropped tail must read back in the ORIGINAL array
  // order — the newest dropped chunk PRECEDES the older chunks (the
  // halving pass always drops from the current array's tail, which is
  // the kept prefix of the previous array). Round 4: the old
  // accumulation appended the new chunk AFTER the prior values, so
  // after dropping [4…7] and then [2…3] the advertised ref held
  // [4…7,2…3] instead of the output contract's verbatim tail [2…7].
  const kept = (result as { pending?: string[] }).pending!;
  assert.deepEqual(dropped, pending.slice(kept.length), "the advertised ref reads back the original verbatim tail, in order");
  // The kept head plus the ref reconciles to the whole registry (the
  // cap costs reads, never data).
  assert.equal(kept.length + dropped.length, pending.length);
  assert.deepEqual([...kept, ...dropped], pending, "head + tail reassemble the original list exactly");
});


test("the wait result variant ACCEPTS referenced (round 3: the handler attaches it, the validator used to forbid it)", () => {
  const base = {
    action: "wait",
    projectDir: "/tmp/w",
    output: [],
    outputTruncated: false,
    pending: [],
    checkpoints: [],
    completed: ["c1"],
    drained: true,
    timedOut: false,
    truncated: { pending: { elided: 3, ref: "w-abc:t1" } },
    referenced: { "w-abc:t1": ["c4", "c5", "c6"] },
  };
  const parsed = replToolOutputShape.safeParse(base);
  assert.ok(parsed.success, JSON.stringify(parsed.error?.issues ?? null));
  // The eval variant keeps accepting referenced too (unchanged).
  const evalParsed = replToolOutputShape.safeParse({
    action: "eval",
    projectDir: "/tmp/w",
    output: [],
    outputTruncated: false,
    pending: [],
    checkpoints: [],
    completed: [],
    referenced: { "w-abc:t1": ["c4"] },
  });
  assert.ok(evalParsed.success, JSON.stringify(evalParsed.error?.issues ?? null));
});

test("truncation refs are WORKSPACE-NAMESPACED and resolve only in their owning store", () => {
  const storeA = new TruncationRefStore("proj-a-111111111111");
  const storeB = new TruncationRefStore("proj-b-222222222222");
  const refA = storeA.set(["a1", "a2"]);
  const refB = storeB.set(["b1"]);
  assert.equal(refA, "proj-a-111111111111:t1", "the ref id carries the workspace namespace");
  assert.equal(refB, "proj-b-222222222222:t1", "each workspace's sequence starts at t1 under its own namespace");
  assert.notEqual(refA, refB, "the ids never collide across workspaces");
  // The projectless-status search (resolveRefs' scan across contexts)
  // finds the ref ONLY in the store that advertised it.
  assert.deepEqual(storeB.get(refA), undefined, "project A's ref never resolves in project B's store");
  assert.deepEqual(storeA.get(refB), undefined, "project B's ref never resolves in project A's store");
  assert.deepEqual(storeA.get(refA), ["a1", "a2"], "the owning store resolves it");
});

test("the store NEVER evicts advertised refs (round 3: the old 16-ref ring dropped still-advertised refs — the cap costs reads, never data)", () => {
  const store = new TruncationRefStore("proj-c-333333333333");
  const refs: string[] = [];
  for (let i = 1; i <= 40; i++) {
    refs.push(store.set([`value-${i}`]));
  }
  // Every ref — including the very first — remains readable past any
  // former ring bound.
  assert.equal(refs.length, 40);
  for (const [index, ref] of refs.entries()) {
    assert.deepEqual(store.get(ref), [`value-${index + 1}`], `ref ${ref} was never evicted`);
  }
});

test("reset clears the store (round 3: old workspace metadata must not remain retrievable after the tool reported the workspace state was dropped)", () => {
  const store = new TruncationRefStore("proj-d-444444444444");
  const ref = store.set(["stale-tail"]);
  assert.deepEqual(store.get(ref), ["stale-tail"]);
  store.clear();
  assert.deepEqual(store.get(ref), undefined, "the dropped workspace's refs are gone");
  // The store keeps working for the fresh workspace (a new sequence
  // under the same namespace — the ref id space never collides because
  // the old refs are gone).
  const fresh = store.set(["fresh-tail"]);
  assert.equal(fresh, "proj-d-444444444444:t2");
  assert.deepEqual(store.get(fresh), ["fresh-tail"]);
});
