/**
 * Phase-F review round 3 pins for the repl tool's structured-output cap
 * and its truncation-reference store:
 *
 * - the `wait` result variant ACCEPTS `referenced` (round 3: the wait
 *   handler attaches it when refs are requested, but the output
 *   validator's wait branch forbade the field — the produced shape was
 *   rejected with "output does not match a repl result variant"),
 * - refs are WORKSPACE-NAMESPACED (`<project-key>:t<seq>`): a ref from
 *   one project resolves only in its own workspace's store (round 3:
 *   every workspace issued bare `t1`/`t2` ids and the projectless
 *   status search returned the first matching ref across contexts — a
 *   ref from one project could silently return another project's data),
 * - the store NEVER EVICTS an advertised ref (round 3: the old 16-ref
 *   ring dropped still-advertised refs, and the ephemeral
 *   completion/output tails cannot be regenerated by re-reading current
 *   state),
 * - `reset` clears the store (round 3: reset dropped the VM and the
 *   disk store but never cleared `truncationRefs` — old workspace
 *   metadata stayed retrievable after the tool reported the workspace
 *   state was dropped).
 */

import assert from "node:assert/strict";
import { test } from "node:test";

import { replToolOutputShape } from "../src/index.js";
import { TruncationRefStore } from "../src/repl-project.js";

test("the wait result variant ACCEPTS referenced (round 3: the handler attaches it, the validator used to forbid it)", () => {
  const base = {
    action: "wait",
    projectDir: "/tmp/w",
    output: [],
    outputTruncated: false,
    pending: [],
    checkpoints: [],
    completed: ["c1"],
    drained: true,
    timedOut: false,
    truncated: { pending: { elided: 3, ref: "w-abc:t1" } },
    referenced: { "w-abc:t1": ["c4", "c5", "c6"] },
  };
  const parsed = replToolOutputShape.safeParse(base);
  assert.ok(parsed.success, JSON.stringify(parsed.error?.issues ?? null));
  // The eval variant keeps accepting referenced too (unchanged).
  const evalParsed = replToolOutputShape.safeParse({
    action: "eval",
    projectDir: "/tmp/w",
    output: [],
    outputTruncated: false,
    pending: [],
    checkpoints: [],
    completed: [],
    referenced: { "w-abc:t1": ["c4"] },
  });
  assert.ok(evalParsed.success, JSON.stringify(evalParsed.error?.issues ?? null));
});

test("truncation refs are WORKSPACE-NAMESPACED and resolve only in their owning store", () => {
  const storeA = new TruncationRefStore("proj-a-111111111111");
  const storeB = new TruncationRefStore("proj-b-222222222222");
  const refA = storeA.set(["a1", "a2"]);
  const refB = storeB.set(["b1"]);
  assert.equal(refA, "proj-a-111111111111:t1", "the ref id carries the workspace namespace");
  assert.equal(refB, "proj-b-222222222222:t1", "each workspace's sequence starts at t1 under its own namespace");
  assert.notEqual(refA, refB, "the ids never collide across workspaces");
  // The projectless-status search (resolveRefs' scan across contexts)
  // finds the ref ONLY in the store that advertised it.
  assert.deepEqual(storeB.get(refA), undefined, "project A's ref never resolves in project B's store");
  assert.deepEqual(storeA.get(refB), undefined, "project B's ref never resolves in project A's store");
  assert.deepEqual(storeA.get(refA), ["a1", "a2"], "the owning store resolves it");
});

test("the store NEVER evicts advertised refs (round 3: the old 16-ref ring dropped still-advertised refs — the cap costs reads, never data)", () => {
  const store = new TruncationRefStore("proj-c-333333333333");
  const refs: string[] = [];
  for (let i = 1; i <= 40; i++) {
    refs.push(store.set([`value-${i}`]));
  }
  // Every ref — including the very first — remains readable past any
  // former ring bound.
  assert.equal(refs.length, 40);
  for (const [index, ref] of refs.entries()) {
    assert.deepEqual(store.get(ref), [`value-${index + 1}`], `ref ${ref} was never evicted`);
  }
});

test("reset clears the store (round 3: old workspace metadata must not remain retrievable after the tool reported the workspace state was dropped)", () => {
  const store = new TruncationRefStore("proj-d-444444444444");
  const ref = store.set(["stale-tail"]);
  assert.deepEqual(store.get(ref), ["stale-tail"]);
  store.clear();
  assert.deepEqual(store.get(ref), undefined, "the dropped workspace's refs are gone");
  // The store keeps working for the fresh workspace (a new sequence
  // under the same namespace — the ref id space never collides because
  // the old refs are gone).
  const fresh = store.set(["fresh-tail"]);
  assert.equal(fresh, "proj-d-444444444444:t2");
  assert.deepEqual(store.get(fresh), ["fresh-tail"]);
});
